---@type LazySpec
return {
  -- "zbirenbaum/copilot.lua",
  -- cmd = "Copilot",
  -- event = "BufEnter",
  -- opts = {
  --   suggestion = {
  --     enabled = true,
  --     auto_trigger = true,
  --     debounce = 150,
  --     keymap = {
  --       accept = "<C-;>",
  --       accept_word = false,
  --       accept_line = false,
  --       next = "<M-]>",
  --       prev = "<M-[>",
  --       dismiss = "<C-]>",
  --     },
  --   },
  --   -- copilot_node_command = vim.fn.expand("$HOME") .. "/.config/nvm/versions/node/v18.18.2/bin/node", -- Node.js version must be > 18.x
  --   copilot_node_command = vim.fn.expand("$HOME") .. "/.nvm/versions/node/v18.16.0/bin/node", -- Node.js version must be > 18.x
  -- },
}
